name: glados-checkin-for-http

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  35 8 * * * 

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        python3 checkin.py '${{ secrets.COOKIE }}'
      env: 
        COOKIE: ${{ secrets.COOKIE }}
